### ISSUE TITLE
Triple Iron Ingot

### ISSUE THREAD

**Issue by kreezxil** [fisty256/AFFS#2]
The triple iron ingot, a shapeless recipe, overrides a shaped recipe that uses 3 iron in an upside down bucket format from Tech Stack's Heavy Machinery mod for the item 'cam shaft'. I suspect that the your recipe is being accessed in the wrong init phase which is preventing the shaped recipe from working.

**Comment by fisty256** [comment]
I just released 1.2.1, should be fixed. :)
